apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spring-boot-aggregator-loom-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Project for spring-boot-aggregator-loom applications
  # Repos Git autorisés
  sourceRepos:
    - git@github.com:kaninda/spring-boot-aggregator-loom.git
  # Destinations autorisées
  destinations:
    - namespace: user-service-dev
      server: https://kubernetes.default.svc
    - namespace: order-service-dev
      server: https://kubernetes.default.svc
    - namespace: loyalty-service-dev
      server: https://kubernetes.default.svc
    - namespace: aggregator-service-dev
      server: https://kubernetes.default.svc
  # Ressources autorisées (optionnel mais propre)
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: ServiceAccount
    - group: gateway.networking.k8s.io
      kind: HTTPRoute